// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxeppqhaarweiknvyvaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZXBwcWhhYXJ3ZWlrbnZ5dmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODUzNTIsImV4cCI6MjA2NTQ2MTM1Mn0.-bAf9OFdbEADDMnVRi_pS2boCW-9Wncd902B8dUVxmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);